[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--all-targets",
    "--all-features",
    "--color", "always",
    "--",
    "-D", "warnings",
    "-D", "clippy::all",
    "-D", "clippy::pedantic",
    "-D", "clippy::nursery",
    "-D", "clippy::cargo",
]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = true

[defaults]
job = "clippy"
